### ISSUE TITLE
화이트리스트 관리 방식 JSON → YAML 전환 및 서브넷 마스크 지원 기능 추가

### ISSUE THREAD

**Issue by limehee** [kgu-clab/clab-platforms-server#527]
### Describe

현재 엔드포인트 접근 제어를 위해 JSON 파일로 관리되고 있는 화이트리스트를 YAML 형식으로 전환하려 합니다. 이 작업은 작업 환경에 따라 부여된 IP를 보다 효율적으로 관리하고, 가독성과 유지보수성을 향상시키기 위함입니다. YAML은 JSON에 비해 문법이 간단하고, 카테고리별로 데이터를 구분하여 관리하기에 용이합니다. 또한 YAML은 주석을 지원하여, IP 추가 이유나 날짜를 기록하여 관리할 수 있습니다. 이와 더불어 서브넷 마스크 지원을 추가하여 동일 네트워크 내의 IP들을 효율적으로 관리할 수 있게 합니다.

### Tasks

1. **화이트리스트 관리 방식 전환**
    - 현재 JSON 파일로 관리되고 있는 화이트리스트를 YAML 파일로 전환합니다.
    - 기존 JSON 파일에서 데이터를 변환하여 새로운 YAML 파일에 적용합니다.

2. **카테고리 분류**
    - YAML 파일 내에서 고정된 IP와 외부 사용 IP를 구분할 수 있는 카테고리를 추가합니다.
```yaml
whitelist:
  fixedIps:
    - "192.168.0.1" # 김씨랩 고정 IP
    - "192.168.0.2" # 김관희 고정 IP
  temporaryIps:
    - "203.0.113.1" # 외부 사용 IP - 김씨랩, 2024-09-02
    - "203.0.113.2" # 외부 사용 IP - 김관희, 2024-09-02
```

3. **서브넷 마스크 지원 추가**
    - 서브넷 마스크를 지원하여 동일 네트워크의 IP 범위를 한 번에 관리할 수 있게 합니다.
```yaml
whitelist:
  fixedIps:
    - "192.168.0.1/24" # 김씨랩 고정 IP (서브넷 마스크 지원)
    - "192.168.0.2"    # 김관희 고정 IP
  temporaryIps:
    - "203.0.113.1/32" # 외부 사용 IP - 김씨랩, 2024-09-02
    - "203.0.113.2"    # 외부 사용 IP - 김관희, 2024-09-02
```
